### ISSUE TITLE
RNG Manipulation on Fishing.

### ISSUE THREAD

**Issue by utilitychase** [Earthcomputer/clientcommands#117]
I don't know if this is possible, but it would be a good idea for the new update. It would make it very simple to get a book with Mending after doing AFK Farming or something like that.

**Comment by Earthcomputer** [comment]
This is one thing I've been wanting to do for a while.

**Comment by Kuratius** [comment]
What would the process for this look like?
Equip fishing rod in the off-hand, cast it, drop items until the rng advances to the desired point?
Or do you need to have the right seed when casting it?

**Comment by Anunayj** [comment]
A little late, but I thought fishing rng was bobber entitiys's rng object, and won't that be changed/recreated everytime the fish is cast. So how would you predict it?

**Comment by Earthcomputer** [comment]
One of the first things done by an entity RNG is generate its UUID, which is then directly sent to the client. The UUID on its own is enough information to uniquely determine the seed instantly. This lets you know what you could possibly catch, immediately when you cast the rod, rather than having to wait 20 seconds to find out. If it's something you don't like, recast the rod. The only caveat is that due to network lag, you can't control exactly what tick you catch the fish, even on singleplayer. But if you ask me, a 1/20 chance to get a mending book is better than nothing.

**Comment by Earthcomputer** [comment]
Delivered

**Comment by SeasonalFerret** [comment]
Lmao literally the first time I tried this, I got a lure 3 unbreaking 3 luck of the sea 3 mending 1 fishing rod... like not even 10 seconds. First try. 

This is amazing. This is absolutely insanely amazing. 

`/cfish add-enchanted-goal minecraft:enchanted_book with minecraft:mending *` Got 4 mending books in 2 minutes.
