### ISSUE TITLE
Improve /cbook command?

### ISSUE THREAD

**Issue by sav3nwarrioR** [Earthcomputer/clientcommands#12]
Some servers fixed dupe books just by disabling 'Sign' button (if you press it - book doesn't sign and/or you get kicked from the server). But 'Forgehax' (Minecraft cheat client) doesn't need you to sign book - Forgehax does it automatically. I guess it would be better if '/cbook' command was able to sign books automatically.

**Comment by Earthcomputer** [comment]
Servers can't disable buttons, they have probably just disabled signing of large books, which no mod could workaround. Instead what you have to do is not sign the books, full book and quills work too.
Since you need many copies of the same book, /cbook offers a `seed` argument which lets you generate the same book and quill every time, on servers that don't let you sign the book.
To generate a book of type 1, you can do `/cbook random 50 1` and for type 2 you can do `/cbook random 50 2` (the "50" here indicates you're filling 50 pages).
