### ISSUE TITLE
how to use /cenchant

### ISSUE THREAD

**Issue by SmirDeNutella** [Earthcomputer/clientcommands#21]
i dont know how the command really works plus when i think its right it says "you need to be in crack state Cracked" please could you help??

**Comment by Anunayj** [comment]
In order to use enchantment manipulation you need to first find the player RNG seed, which can be found by finding 3 consecutive XP seeds (This might not be correct check with Earth) , to find these first set `/ctemprule set enchantingPrediction true`
Go to a enchanting table, put random enchantable items in the table till the XP seed is found (Indicated by the GUI), then enchant a dummy item and do this again (and enchant the item again) then do this again to finally find the Player seed. Once you have done this successfully you will be in the Cracked State. Now you can use the /cenchant and Unbreaking manipulate

**Comment by leumasme** [comment]
With the new update, you can now also use
/ccrackrng
wich autocracks your seed with the slight randomization in item drops.
From there, use
/cenchant YOURITEM \[with \<enchantmentname\> \<enchantlevel|\*\>\] \[without \<enchantname\>\<enchantlevel|\*\>]
both with and without are optional, but if used, name and level after them are required.
with and without can be appended as many times as you want at the end.
Close Issue?

**Comment by Earthcomputer** [comment]
I'm planning on writing a proper wiki for clientcommands soon, so this kind of question can be easily answered. But for now, Anunayj and leumasme have answered this question, so I will close this issue ;)
