### ISSUE TITLE
`/cfinditem --no-search-shulker-box` doesnt actually exclude shulker boxes

### ISSUE THREAD

**Issue by Domkeykong** [Earthcomputer/clientcommands#218]
Shulker-Boxes are included in the search for the item, when using `--no-search-shulker-box` to exclude them.

**Comment by James103** [comment]
To be more specific, `/cfinditem --no-search-shulker-box` only removes shulker boxes from the search space if they are inside of an(other) inventory, not placed in the world.

**Comment by Earthcomputer** [comment]
By default. if you for example have a shulker box item in a chest, `/cfinditem` will find items inside that shulker box item inside that chest. `--no-search-shulker-box` prevents this behaviour, so that you only find items directly in chests etc and not in shulker boxes that are inside chests. The `--no-search-shulker-box` flag is *not* meant to prevent searching shulker boxes that are in the world.

This reminds me, I have to take into account bundle items in 1.17, which gives me an opportunity to rename this flag then to be less confusing.

**Comment by James103** [comment]
> This reminds me, I have to take into account bundle items in 1.17, which gives me an opportunity to rename this flag then to be less confusing.

An idea for the new name is `--no-search-nested-inventory`, where `nested-inventory` is not just shulker boxes, but also bundles and any other items that can hold items within, but is itself placed as an item in a slot inside a top-level inventory.
