### ISSUE TITLE
Don't report Enchant cracker issues here

### ISSUE THREAD

**Issue by BraveCaperCat** [Earthcomputer/clientcommands#378]
Report them at [EnchantmentCracker](https://github.com/Earthcomputer/EnchantmentCracker)

**Comment by BraveCaperCat** [comment]
Probably .jar issues here

**Comment by xpple** [comment]
Hey, I appreciate the announcement you made! This repository is indeed for the Minecraft Fabric mod called "clientcommands", and not for the standalone Java application called "EnchantmentCracker". Even though some people are confused about this difference, as they assume EnchantmentCracker is supposed to be run as a mod, I don't think this is the way to tackle that misconception. You can leave that to the repository owner. One thing to keep in mind though is that some people may misinterpret your help as spammy or even annoying, which is obviously not your intention! I know this because you stated your age somewhere, which makes it perfectly natural and understandable. My advise is to be a little bit less enthusiastic and impulsive because those behaviours often clash with a somewhat professional medium like GitHub.
