### ISSUE TITLE
/cenchant command not working when enchanting books

### ISSUE THREAD

**Issue by noahbclarkson** [Earthcomputer/clientcommands#421]
Have been using the cenchant command on a vanilla server and it's been working perfectly except for books. I can't seem to get them to work. It says to put it in a slot but when I enchant the book it isn't the correct enchantment. I'm running on 1.19 with version 2.7. Other items are working fine. (I'm trying to enchant a book with feather falling 4).

**Comment by m-sarabi** [comment]
I also have some the problem using this command in 1.19 for other items.
I tried enchanting pickaxes and sometimes it said 14 bookshelves and slot 3. but 14 gave the wrong enchants, 15 bookshelves gave me the correct enchants.
Also Enchanting swords with 5 Enchants gave me wrong results most of the time.

**Comment by HaphLife** [comment]
I've had a similar issue, I believe that mine it has to do with how many items get dropped by the mod, because I noticed that the success rate for me varies depending on how many items were thrown (less than a stack almost always works, 4+ stacks almost never works) perhaps occasionally packets get lost?

Books just happen to be an item that have vary many possible enchants, so it takes way more manipulation to get to the target. Enchanting a sword with 5 enchants would have a similar issue.

Perhaps this could be fixed by slowing down near the end and checking that the item motion is the expected directions (like when using ccrack) to check that the exactly correct number of items were dropped?

**Comment by Earthcomputer** [comment]
Should be fixed by https://github.com/Earthcomputer/clientcommands/commit/e7b9ec1fe526571d026603fac29894ed138cfab1
