### ISSUE TITLE
Fish mainpulation not working with mending books

### ISSUE THREAD

**Issue by HastumeM** [Earthcomputer/clientcommands#492]
/cfish command did not work when getting enchanted book of mending, as shown below:
MC version: 1.19.3
Mod version: 2.7.8
The fishing rod had enchantments of mending, unbreaking 3, lure 3, luck of the sea 3
At first fishing it may succesful, and then it stops working. Normal attemp of fishing enchanted book with no specified enchantment works. It also works when removing the 'exactly'. I'm using '/cfish add-enchanted-goal minecraft:enchanted_book(or 'minecraft:book') with minecraft:mending * exactly' for the pics below
![Screenshot_2](https://user-images.githubusercontent.com/62732240/211283728-b07f9dbd-e049-4a66-bd6b-0a9a72a1a2a0.png)
![Screenshot_3](https://user-images.githubusercontent.com/62732240/211284030-9d5f95c0-2384-46b7-b959-bf02263bcf46.png)
![Screenshot_4](https://user-images.githubusercontent.com/62732240/211284041-1a4afb71-f103-4c61-8628-43e13ce4117c.png)

**Comment by hube12** [comment]
Enchantment on the rod might be the cause, could you confirm that on unenchanted rod this never happens?

**Comment by HastumeM** [comment]
No, in fact using non-enchanted fishing rod was even impossible to fish anything. When i cast it says fishing bobber out of water which i can clearly see its right under the lily pad like below
![Screenshot_5](https://user-images.githubusercontent.com/62732240/211290141-8d91ca89-2b8b-44bf-bbf9-9ea2ac685959.png)

**Comment by HastumeM** [comment]
Another situation is the fishing bobber is actually out of water, but the mod gives no warns and tries to fish when the bobber is out of water(not under lily pad)

**Comment by Earthcomputer** [comment]
I think the cause is that it can sometimes be the case that the bobber's position can be slightly different on the client vs the server. But anyway back to the original issue. The error message is clearly wrong, I will look into it. I did test mending books and they worked without `exactly`, although admittedly I didn't test luck of the sea.

**Comment by Earthcomputer** [comment]
I can't reproduce this. I am getting mending fairly consistently both with and without luck of the sea 3, with the exact goal that you posted in your original issue. Please remember the caveats to fishing manipulation, which are that it's not 100% reliable due to network lag, and that it doesn't work on some server software. It can sometimes take a few tries before it automatically calibrates to your network, and even then it won't be perfectly reliable, even in singleplayer.

**Comment by Lawerencium** [comment]
eventhough its closed... 
I've got a similair issue, the rod goes at it, then finally stops the rod-spamming... when it comes out it will give something completely different from the fishing goal.

So, i give lillypad as goal, and it just gives stuff like cod or salmon. any ideas on that?

**Comment by Earthcomputer** [comment]
See my previous comment.

**Comment by PureFallen** [comment]
I have been running into a similar issue today.
MC Version: 1.19.3
Mod Version: 2.7.8

Troubleshooting i took was:
- Downloading a Backup of the Server to host at localhost
- Hosting a clean Vanilla Server at localhost
- Replacing JRE for Server and Client
- Replacing JVM Arguments for Server and Client
- Messing with FPS/VSYNC
- Downgrading Fabric API on Client

Unfortunately, i was not able to get `/cfish add-enchanted-goal minecraft:book with minecraft:mending 1` work consistently. 

The error behavior is kinda weird: The first cast after starting the game causes significant frame drop.
- When the cast succeeds, the fishingManipulation continues to work like i am used to from 1.19.2 and earlier
- When the cast fails, it will keep failing until the game is restarted
When changing the goal afterwards to a way easier to achieve goal, the fishing works but the casting speed is greatly reduced...?

I can't reproduce the same error on 1.19.2 using 2.7.5, so i wonder if the issue is related to how the fishingManipulation crash was fixed for 1.19.3...
A certainly got no idea with how inconsistent the error is, and with it only affecting items of a certain rarity. I can fish for `enchanted_rods` rather consistently, without a lot of rod_spamming and the frame drop at the beginning of the manipulation.

https://youtu.be/gM_iYUv77cg
