### ISSUE TITLE
`/cgetdata item` command

### ISSUE THREAD

**Issue by ErrorNoInternet** [Earthcomputer/clientcommands#503]
Will display the NBT data for the held item (or specified slot)
Currently possible by using `/cgetdata entity @s Inventory`

**Comment by xpple** [comment]
Since it's indeed already possible, I don't see the point of adding a new subcommand. If you really want to get the data of a certain slot you can specify the index of the slot by doing `/cgetdata entity @s Inventory[<index>]`. The slots are arranged according to the image below. Keep in mind that you have to specify the _index_ of the slot, not the slot itself.
![image](https://user-images.githubusercontent.com/49305700/219617220-720468ae-d7a0-41c2-9449-f80ec2932e0e.png)
