### ISSUE TITLE
Distances for /cfind and /cfindblock have unnecessary precision

### ISSUE THREAD

**Issue by joendter** [Earthcomputer/clientcommands#506]
Nobody needs 10 digits precision in mc in 99% of cases and if you do need it it should be optional. All this extra precision just makes the distance statement confusing.
![image](https://user-images.githubusercontent.com/71767955/221203181-82859b42-3482-4209-b3a1-88216738f1c5.png)
(first is /cfindblock, second is /cfind)
I'm using version 2.7.5 because 1.19.2

**Comment by xpple** [comment]
You are right, and this is actually implemented into clientcommands already. I have no idea however why it isn't working as it should. See [here](https://github.com/Earthcomputer/clientcommands/blob/fabric/src/main/resources/assets/clientcommands/lang/en_us.json#L55) for the relevant line.

Edit: It turns out that Minecraft uses its own formatting, which is not the same as `String.format`.
