### ISSUE TITLE
About "/cenchant", the enchantments need modification.

### ISSUE THREAD

**Issue by Solitudream** [Earthcomputer/clientcommands#541]
"/cenchant" need remove thorns(for helmet, leggings and boots), sharpness, bane of arthropods and smite(for axe), because they couldn't be enchanted at the enchanting table.

**Comment by hube12** [comment]
This was fixed in https://github.com/SeedFinding/mc_feature_java/commit/c15315b83be310b5fe4af7eb550304ff8526d1d5#diff-ee287d4eadbb4f860d67516668e178aa2aba27b789ca7c4325d22eb23bc0aa28

**Comment by xpple** [comment]
I will reopen the issue until the fix has been implemented in clientcommands.

**Comment by PurPur134** [comment]
This doesn't appear to be fixed in Version 2.8.2. See the screenshot below demonstrating that the command still allows for diamond leggings to be enchanted with Thorns from the enchanting table, which is not possible.
![2023-07-15_17 35 54](https://github.com/Earthcomputer/clientcommands/assets/139658227/afab8259-1ace-4c91-acd8-f54f9adce0eb)
