### ISSUE TITLE
Server Lag Desyncs RNG / Breaks infiniteTools

### ISSUE THREAD

**Issue by leumasme** [Earthcomputer/clientcommands#59]
If the Server is slightly laggy and you break multiple blocks in a lag spike, infiniteTools will desync the RNG. A possible "solution" might be (if i understand the problem correctly) to make clientcommands cancel breaking a block at the end of the break animation if the item drops from the previous block break have not gone through yet.

**Comment by Earthcomputer** [comment]
This is a difficult problem. Waiting until the item is dropped would first of all break instant mining and second of all cause issues for blocks which don't drop any items, especially if the server is running a custom datapack.

Another idea is to self-correct when the server puts the blocks back where you just mined. In the case of server lag this might actually mean you don't lose any durability, but in the case of instant mining there's still ghost blocks. In 1.14 to 1.14.3 ghost blocks were "fixed" by correcting the client if it thinks it's mined a block but hasn't, which would make this fix work (but you might lose a couple of durability before the server corrects you). In 1.14.4 Mojang messed up and reintroduced ghost blocks so that wouldn't work anymore. Apparently they fixed that again in the snapshots but I haven't looked into how.

And even then, how do we know that the block was replaced by the server and not by something else, like another player? It would break in snow farms where the snow is replaced instantly by the snow golem.

**Comment by dk88711** [comment]
For me, the desync is actually not happened very often. It desyncs every 5-10 minutes. I notice the durability drops then I know the RNG desyncs. I just type /ccrackrng again to fix it, then I can use another 5-10 minutes for no durability drops. However, it is usually too late for me to notice the RNG desyncs, and the durability is already dropped a lot.

So, what I suggest is, the current mechanic for maintaining tools durability is already good enough, no need to modify for self-correct. Instead we might add a notification to tell the player to stop breaking blocks, whenever durability drops is detected (of course only during "after /ccrackrng state" and infiniteTools is true). An extra temprule clould be add like "/ctemprule set toolBreakAutoStop". What it does is: 
(when player current holding tool durability drops) => {
    show a message in chat or actionbar; 
    if (player is holding left (i.e. breaking block)){ 
        release the left button (but when player can still re-press the left button to break blocks ); } }

**Comment by dk88711** [comment]
So, in emergency situation, player is still able to break the blocks they want (e.g. palyer is being chased, no time to type /ccrackrng, just let the durability drops is fine). When player is breaking a large region of blocks, usually they are just holding the left click, we stop that and tell them to /ccrackrng again. Although we can't save every single bit of durability, but it can already last long enough to use. 

(extra notes: Even though we detected durability drops, if player decided to keep going, the "throwing item" process may still continue, we can just stop it again if another durability drops is detected. As in my case, after I /ccrackrng and temprule true, the first block might cause durability to drop 1 but later on no more durability loses.)

**Comment by MCRcortex** [comment]
having the /ccrackrng going while players are changing the rng would require a major overhaul in the cracker itself, the lattice expects the rng calls to be 4 (inclusive) calls apart. While it is possible to make it dynamic call spacing, the effort to do so far outweighs the gains

**Comment by Earthcomputer** [comment]
How about changing the `toolBreakWarning` TempRule from a boolean with a hardcoded durability threshold, to an integer threshold you can set yourself?
- To disable `toolBreakWarning`, set it to 0.
- To have `toolBreakWarning` at a sensible level without infinite tools, set it to 20.
- To use `toolBreakWarning` with infinite tools, set it to 99999999.

**Comment by dk88711** [comment]
> having the /ccrackrng going while players are changing the rng would require a major overhaul in the cracker itself, the lattice expects the rng calls to be 4 (inclusive) calls apart. While it is possible to make it dynamic call spacing, the effort to do so far outweighs the gains

Just having soft warning showed if durability drops detected when infiniteTools is activated. And it would be nice if it could further simulate releasing [Attack/Destroy] key if the key is pressed.

**Comment by Earthcomputer** [comment]
Seems to be fixed in vanilla by now
