### ISSUE TITLE
"Player Hurt" RNG Crack Reset Reason triggers without damage to player

### ISSUE THREAD

**Issue by leumasme** [Earthcomputer/clientcommands#61]
the "Player Hurt" Restart Reason seems to commonly falsetrigger when crouching in an 1 block high space and then coming out and standing back up.
Lag might also be a factor.

**Comment by Earthcomputer** [comment]
I was not able to reproduce this myself without the player actually getting hurt. When I decreased the server tick rate to simulate lag I was able to get the player to hurt when "swimming" in a 1-high gap. With good armour you still may have 10 hearts, but that still counts as a player hurt. 

Since this seems to be caused by the player taking damage serverside, this just looks like clientcommands' safety measure doing it's job, and there isn't much more I can do about it.
