### ISSUE TITLE
cenchant: Remove Enchants from "without" autocomplete that are exclusive with "with" enchantments.

### ISSUE THREAD

**Issue by leumasme** [Earthcomputer/clientcommands#71]
Ex:
/cenchant diamond_boots with minecraft:protection 4 without [ COMPLETION ]
clientcommands also suggests enchantments that are exclusive with protection 4

**Comment by Earthcomputer** [comment]
Works as intended.
It's redundant, but you are allowed to specify that you don't want an enchantment that would be impossible anyway.

- `/cenchant diamond_boots with protection 4 without protection 3` is *valid*, because you can get protection 4 boots without protection 3.
- `/cenchant diamond_boots with protection 4 without blast_protection 4` is *valid*, because you can get protection 4 boots without blast protection 4.
- `/cenchant diamond_boots with protection 4 without protection 4` is *invalid*, because you can't get protection 4 boots without protection 4.
- `/cenchant diamond_boots with protection 4 without protection *` is *invalid*, because you can't get protection 4 boots without protection.
- `/cenchant diamond_boots with protection * without protection 1` is *valid*, because you can get protection boots without protection 1.

The autocompletion already handles all of these correctly. Hope this clears it up.
