### ISSUE TITLE
[Newest Version] Don't have "Manipulate Tab"

### ISSUE THREAD

**Issue by fyxisShazad** [Earthcomputer/clientcommands#90]
When i get 2 enchantment seeds cracked i dont't have a https://youtu.be/Bl2lan-44H8?t=140

"Manipulate" button, why's that ?

**Comment by MCRcortex** [comment]
Are you using 1.12 or 1.14.4? 1.12 is no longer supported

**Comment by fyxisShazad** [comment]
1.14.4

**Comment by Earthcomputer** [comment]
The "manipulate" button never existed, that was a different mod in the video, which was hacked together then dropped because it never worked properly.
Instead, you can use the `/cenchant` command. Here's some examples:
```
/cenchant diamond_pickaxe with efficiency 4 with unbreaking 3 with silk_touch *
/cenchant diamond_sword with unbreaking 3 without bane_of_arthropods *
```
You can also use the `--simulate` flag to test what enchantments you'd get without actually doing anything:
```
/cenchant --simulate iron_shovel with efficiency * without efficiency 1 with unbreaking 3
```
Once you've run the command, wait for all the items (if any) to be thrown, then follow the instructions in chat.
