### ISSUE TITLE
player rng changing

### ISSUE THREAD

**Issue by ghost** [Earthcomputer/clientcommands#92]
using an item with unbreaking will change the rng, but it doesnt notify the user

video: https://youtu.be/UzyZ6FCEpFw

**Comment by Earthcomputer** [comment]
This is because, when the RNG is cracked, in some cases (like using an unbreaking tool) the client can keep track of what the RNG is changed to, so it doesn't need to re-crack the RNG or bother the user with those details. If you are really interested in when the RNG changes, you can disable this "smart" behaviour by using `/ctemprule set playerRNGMaintenance false`
